---
assignments_2_student:
  state: hidden
  display_name: Assignment Enhancements - Student
  description: Use the new assignments student page
  applies_to: Course
  root_opt_in: true
assignments_2_teacher:
  state: hidden
  display_name: Assignments 2 Teacher View
  description: Use the new assignments teacher page
  applies_to: Course
  root_opt_in: true
  beta: false
  environments:
    production:
      state: disabled
new_math_equation_handling:
  state: hidden
  display_name: 'Math: Updated equation handling'
  description: |-
    Replaces the existing image of the math equation plus its hidden mathml
    with a MathJax processed version. This change provides better accessibility
    and many options for the reader to interact with the equation on the page.
  applies_to: RootAccount
inline_math_everywhere:
  state: hidden
  display_name: 'Math: Support LaTex math equations almost everywhere'
  description: |-
    With this feature, LaTex math equations entered into most
    text entry fields in Canvas will be processed by MathJax.
    LaTex delimited by \(...\) become inline equations, while
    $$...$$ will be rendered as a block.  For example,
    you could choose to title an Assignment \(\sqrt{x}\), or
    enter $$ax^2 + by + c = 0$$ in a submission comment.
    This feature requires that the "Math: Updated equation handling"
    flag is also on.
  applies_to: RootAccount
auto_show_cc:
  state: allowed
  display_name: Auto Show Closed Captions
  description: |-
    Automatically show closed captions in the user's current
    language (if available) when playing canvas media.
  applies_to: User
  autoexpand: true
